{
 "title": "Pods",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "Container Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=~\"eventrouter|.*\", namespace=\"$namespace\", container=\"$container\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (container)(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\",container=~\"$container\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum by(container_name) (container_memory_working_set_bytes{namespace=~\"$namespace\",container_name=~\"$container\", container_name!=\"POD\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "max by (container) (kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\",container=~\"$container\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "CPU Usage (milicores)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max by (container)(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\",container=~\"$container\"})*1000",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum by (container_name)(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container_name=~\"$container\"}[2m])) * 1000",
     "legendFormat": "Current"
    },
    {
     "expr": "max by (container)(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\",container=~\"$container\"})*1000",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name)(rate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod_name=~\"^$container.*$\"}[2m]))",
     "legendFormat": "Current"
    }
   ]
  }
 ]
}